openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  description: Multi-file boilerplate for OpenAPI Specification.
  license:
    name: MIT
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
servers:
  - url: http://petstore.swagger.io/v1
tags:
  - name: pets
paths:
  /pets:
    $ref: "https://raw.githubusercontent.com/yashasvi13/multifile-spec/main/resources/pets.yaml"
  /pets/{petId}:
    $ref: "https://raw.githubusercontent.com/yashasvi13/multifile-spec/main/resources/pet.yaml"
components:
  parameters:
    $ref: "https://raw.githubusercontent.com/yashasvi13/multifile-spec/main/parameters/_index.yaml"
  schemas:
    $ref: "https://raw.githubusercontent.com/yashasvi13/multifile-spec/main/schemas/_index.yaml"
  responses:
    $ref: "https://raw.githubusercontent.com/yashasvi13/multifile-spec/main/responses/_index.yaml"